version: "3.9"

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb-angular
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root123
      MARIADB_DATABASE: demo_db
      MARIADB_USER: demo_user
      MARIADB_PASSWORD: demo_pass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  mariadb_data:
